//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pampa.InSol.Biz.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pampa.InSol.Biz.Recursos.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de validación.
        /// </summary>
        public static string ErrorValidacion {
            get {
                return ResourceManager.GetString("ErrorValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &apos;{0}&apos; debería ser antes del&apos;{1}&apos;.
        /// </summary>
        public static string FechaDeberiaEstarAntesDe {
            get {
                return ResourceManager.GetString("FechaDeberiaEstarAntesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &apos;{0}&apos; debería ser despues del &apos;{1}&apos;.
        /// </summary>
        public static string FechaDeberiaEstarDespuesDe {
            get {
                return ResourceManager.GetString("FechaDeberiaEstarDespuesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al guardar {0}.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Jumbo {0} seleccionada para editar no existe.
        /// </summary>
        public static string JumboEditNotFound {
            get {
                return ResourceManager.GetString("JumboEditNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &apos;{0}&apos; no puede tener mas de &apos;{1}&apos; caracteres!.
        /// </summary>
        public static string MaximoTamaño {
            get {
                return ResourceManager.GetString("MaximoTamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &apos;{0}&apos; debe ser mayor a &apos;{1}&apos;!.
        /// </summary>
        public static string MaximoValor {
            get {
                return ResourceManager.GetString("MaximoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &apos;{0}&apos; no puede tener menos de &apos;{1}&apos; caracteres!.
        /// </summary>
        public static string MinimoTamaño {
            get {
                return ResourceManager.GetString("MinimoTamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &apos;{0}&apos; debe ser mayor a &apos;{1}&apos;!.
        /// </summary>
        public static string MinimoValor {
            get {
                return ResourceManager.GetString("MinimoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; debe estar entre &apos;{1}&apos; y &apos;{2}&apos;!.
        /// </summary>
        public static string Rango {
            get {
                return ResourceManager.GetString("Rango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &apos;{0}&apos; es requerido!.
        /// </summary>
        public static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario {0}, no existe o no tiene permisos para acceder al sistema..
        /// </summary>
        public static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no existe..
        /// </summary>
        public static string UserInexistente {
            get {
                return ResourceManager.GetString("UserInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario &apos;{0} {1}&apos; no tiene ningún permiso asociado..
        /// </summary>
        public static string UserSinPermisos {
            get {
                return ResourceManager.GetString("UserSinPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} {1} no tiene permisos para la función {2}.
        /// </summary>
        public static string UserSinPermisos2 {
            get {
                return ResourceManager.GetString("UserSinPermisos2", resourceCulture);
            }
        }
    }
}
